services:

  # =========================
  # LANDING PAGE
  # =========================

  landing-page:
    build:
      context: ./apps/landing-page

    container_name: ai-landing-page

    working_dir: /app

    volumes:
      - ./apps/landing-page:/app

    ports:
      - "8000:5173"

    restart: always

    networks:
      - orm-network


  # =========================
  # ORM FRONTEND
  # =========================

  orm-frontend:
    build:
      context: ./apps/orm-system/frontend

    container_name: orm-frontend

    working_dir: /app

    volumes:
      - ./apps/orm-system/frontend:/app

    ports:
      - "8001:5173"

    restart: always

    depends_on:
      - orm-backend

    networks:
      - orm-network


  # =========================
  # ORM BACKEND
  # =========================

  orm-backend:
    build:
      context: ./apps/orm-system/backend

    container_name: orm-backend

    working_dir: /app

    volumes:
      - ./apps/orm-system/backend:/app

    ports:
      - "8080:8000"

    
    restart: always

    networks:
      - orm-network


  # =========================
  # FACE FRONTEND
  # =========================

  face-frontend:
    build:
      context: ./apps/face-recognition/frontend

    container_name: face-frontend

    working_dir: /app

    volumes:
      - ./apps/face-recognition/frontend:/app

    ports:
      - "8002:5173"

    restart: always

    depends_on:
      - face-backend

    networks:
      - orm-network


  # =========================
  # FACE BACKEND
  # =========================

  face-backend:
    build:
      context: ./apps/face-recognition/backend

    container_name: face-backend

    working_dir: /app

    volumes:
      - ./apps/face-recognition/backend:/app

    ports:
      - "8090:8000"

    restart: always

    networks:
      - orm-network


networks:

  orm-network:
    driver: bridge